# Generated by Django 4.2.7 on 2024-11-12 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_options_alter_product_brand_and_more'),
        ('user', '0003_alter_administrator_options_alter_client_options_and_more'),
        ('shoppingCart', '0004_alter_cartproduct_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartproduct',
            options={'verbose_name': 'Cart Product', 'verbose_name_plural': 'Cart Products'},
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='client',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='user.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantity'),
        ),
    ]
